### ISSUE TITLE
No percentage indication on Windows

### ISSUE THREAD

**Issue by F-I-D-O** [p-ranav/indicators#105]
When I try your very first example on Windows, there is no percentage indicator:
![image](https://user-images.githubusercontent.com/2853732/144750387-71016016-64ce-4e95-9687-c7f39952a924.png)

In PowerShell and Windows console, the progress bar does not even stay on the same line: 
![image](https://user-images.githubusercontent.com/2853732/144750505-9e7badb3-8021-4b37-9f5c-55a2a6c30df3.png)

Is this the normal behavior on windows?

**Comment by Star9daisy** [comment]
Add `option::ShowPercentage(true)` when declaring `ProgressBar`. Then you can see the percentage number coming out.

**Comment by orion160** [comment]
What needs to be done is to update the documentation. Samples are shown without that option, and leads to confusion.
