### ISSUE TITLE
How to construct multiprogress with variable?

### ISSUE THREAD

**Issue by nickhuangxinyu** [p-ranav/indicators#106]
I see the multiprogress construct method as:

`indicators::MultiProgress<indicators::ProgressBar, 3> bars;
`
but I want to init it using a variable, like this:
```
int a = 3;
indicators::MultiProgress<indicators::ProgressBar, a> bars;
```

Can I achieve this? i think dynamic_process has good method like push_back?

**Comment by p-ranav** [comment]
```cpp
int a = 3;
indicators::MultiProgress<indicators::ProgressBar, a> bars;
```

The above is not possible in C++. `MultiProgress` is designed for the case where you know the number of progress bars at compile time. 

For all other cases, I recommend you use `DynamicProgress`

**Comment by couldbejake** [comment]
This is exactly what I was trying to do, I considered using processor directives, I would appreciate this feature.
