### ISSUE TITLE
print to console

### ISSUE THREAD

**Issue by arandomdev** [p-ranav/indicators#107]
Is there a way to print to the console while there is a progress bar? I know there is the stream option, I don't know how this can be used for output.

**Comment by alkis-pap** [comment]
I assume you want to keep the progress bar on the last line while printing new lines above it.

On linux there's an easy method using boost::iostreams. You can change the behavior of std::cout by using a custom streambuf. The line_filter class from boost::iostreams makes it easy to define a function that is used to transform every line being printed. By adding "\n" (new line) "\033[A" (move cursor up) and "\033[1L" (insert line) before each line you can effectively print it above the last line where the progress bar is. The progress bar must be configured to use a stream that behaves like std::cout normally does.

Example code:
```
struct LineInsertingFilter : boost::iostreams::line_filter {
    std::string do_filter(const std::string& line) {
        return "\n\033[A\033[1L" + line;
    }
};

int main() {
    auto* stdout_buf = std::cout.rdbuf(); // get stdout streambuf

    // create a filtering_ostreambuf with our filter and the stdout streambuf as a sink
    boost::iostreams::filtering_ostreambuf filtering_buf{};
    filtering_buf.push(LineInsertingFilter());
    filtering_buf.push(*stdout_buf); 
    
    std::cout.rdbuf(&filtering_buf); // configure std::cout to use our streambuf
    
    std::ostream os(stdout_buf); // create local ostream acting as std::cout normally would
    
    // create progress bar
    indicators::ProgressBar bar {
        // ...
        indicators::option::Stream{os} // use local ostream for progress bar
    };

    bar.set_progress(0);

    std::cout << "This line is inserted above the progress bar..." << std::endl;

    bar.set_progress(50);

    std::cout << "... and this one too." << std::endl;

    bar.set_progress(100);

    std::cout.rdbuf(stdout_buf); // reset std::cout

    std::cout << "This line is printed normally." << std::endl
}
```

**Comment by arandomdev** [comment]
@alkis-pap sorry for the late reply, but your idea worked wonderfully.

Also for future reference, my end goal was to use spdlog and a progress bar simultaneously and adding your terminal codes to the format also works.
For example,
```c++
auto streamSink = std::make_shared<spdlog::sinks::ostream_sink_mt>(std::cout);
streamSink->set_pattern("\n\033[A\033[1L[%H:%M:%S %z] %v");

auto logger = std::make_shared<spdlog::logger>("TestLogger", streamSink);
```

Thanks!
