### ISSUE TITLE
C++17 deprecated codecvt_utf8 breaks build on MSVC with C++20

### ISSUE THREAD

**Issue by jsttzsf** [p-ranav/indicators#117]
Thank you very much for your effort and great library :-) 

### Description
This is very similar to #93. It seems that the fix from this [commit](https://github.com/p-ranav/indicators/commit/e34840ab0d82cda89c31125c3290c5830d00f294) does not work in MSVC with C++20 activated.

Compilation yields the error: 
`indicators\display_width.hpp(283,29): error C4996: 'std::codecvt_utf8<wchar_t,1114111,(std::codecvt_mode)0>': warning STL4017: std::wbuffer_convert, std::wstring_convert, and the <codecvt> header (containing std::codecvt_mode, std::codecvt_utf8, std::codecvt_utf16, and std::codecvt_utf8_utf16) are deprecated in C++17. (The std::codecvt class template is NOT deprecated.) The C++ Standard doesn't provide equivalent non-deprecated functionality; consider using MultiByteToWideChar() and WideCharToMultiByte() from <Windows.h> instead. You can define _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.`

It seems that the #define has no effect in MSVC C++20 

### Steps to reproduce
OS: Win10 x64
Install indicators with vcpkg
Compilation: VS2019 MSVC compile with c++20

If you need any additional information please let me know.

### Expected behavior
Build works on windows with C++20 ;-) 
One could argue that this is an issue with MSVC because it doesn't accept the #define. On the other hand codecvt_utf8 might be fully removed in C++23 and thus maybe a true replacement in the code makes sense? 
Considering that this is an issue as well on gcc (#116) it might be worth doing a full replacement.

**Comment by p-ranav** [comment]
if you confirm that the fix works for you, I'll go ahead and prepare a new release.

**Comment by jsttzsf** [comment]
Thank you very much for your fast response and the quick fix! :-) 

Your fix works but the compiler yields another deprecation warning regarding mbstowcs. I have created a pull request that replaces mbstowcs by mbstowcs_s. May I kindly ask you to review it a give feedback in case something needs to be changed? #119 

Thanks!
