### ISSUE TITLE
ProgressBar::tick() prints progress even if nothing has changed

### ISSUE THREAD

**Issue by amallia** [p-ranav/indicators#13]
From my understanding calling `tick()` method will trigger the print function which will re-print the progress status regardless. Is this correct?
Can I open a PR to update only if something has changed?

https://github.com/p-ranav/indicators/blob/2291c8c39c031dda6007a68f8e725a0be5ba2ca7/include/indicators/progress_bar.hpp#L112-L119

**Comment by p-ranav** [comment]
Since I'm not using a `try_lock`, isn't `_progress` guaranteed to change every time `tick()` is called?

**Comment by amallia** [comment]
I just noticed that _progress is in a [0, 100] range.
I am more familiar with progress bars that accept at construction time the total number of operations to perform, so not only 100 ticks.
In that scenario, if you tick you don’t necessarily change the progress percentage. Makes sense?

**Comment by amallia** [comment]
Actually it seems we can do the above by setting _bar_width, but then the way percentage is computes is a bit odd.

https://github.com/p-ranav/indicators/blob/2291c8c39c031dda6007a68f8e725a0be5ba2ca7/include/indicators/progress_bar.hpp#L236

**Comment by p-ranav** [comment]
Yeah. Progress is in range `[0, 100]` and that really keeps things simple when computing how much of the bar to fill. It is also a notable design decision to keep the bar width decoupled from the number of operations.

To fit your requirements, I recommend using:
```
bar.set_progress(current_progress + 100.0f / num_operations)
```

 and that should work fine as long as `num_operations > 0`.  

I could probably introduce a `.increment_progress_by` method (similar to `.update` in tqdm) to make this less wordy but `.set_progress` is quite explicit.

**Comment by amallia** [comment]
I see. Although I like simple designs too, I do not agree with keeping the range in `[0, 100]`. It just moves the complexity to the application that is using the progress bar. 
On the other hand, having a design which supports my use case within the progress bar would allow anybody to rely on a feature out of the box, without any hack.

**Comment by p-ranav** [comment]
@amallia indicators now supports setting `option::MaxProgress`. This allows for working with use-cases where progress isn't strictly in [0, 100]. Example [here](https://github.com/p-ranav/indicators#working-with-iterables) works with iterables.
