### ISSUE TITLE
In MultiProgress, elapsed time still running even when completed

### ISSUE THREAD

**Issue by thebesttv** [p-ranav/indicators#18]
In the example [MultiProgress](https://github.com/p-ranav/indicators#multiprogress), all the elapsed time of the 3 progresses are running together even when progress 1 and 3 have completed. Is it possible to add something like `_end_time_point` to prevent this?

**Comment by p-ranav** [comment]
Thanks for the issue. 

It probably makes sense to set this as the default behavior - Do not increment elapsed time for a bar in MultiProgress if the bar has completed.
