### ISSUE TITLE
No need to use lock here

### ISSUE THREAD

**Issue by bagobor** [p-ranav/indicators#2]
Awesome project!
But code can be polished a little.
Ex:
https://github.com/p-ranav/indicators/blob/6f69ca5246c5961fbb232531996ab1981c9782ac/include/indicators/progress_bar.hpp#L108

No need to use lock here

**Comment by NikolausDemmel** [comment]
@bagobor, just randomly came across this and I'm curious why you suggest it is ok to skip the lock here? `_progress` is not atomic or anything, so what guarantees that another thread sees updates? To my understanding it might work, but it might also not work for the same reason that a non-atomic boolean flag might work for thread synchronization, but might also not work. What am I missing?

**Comment by bagobor** [comment]
@NikolausDemmel thanks, for pointing it out. I wasn't thinking about data visibility here. And it looks like std::mutex has release-acquire memory ordering semantics.  
But I'll be really nice to have non-blocking access to 'view' representation of cur. progress value. That's my point here.  :)
