### ISSUE TITLE
"error: 'mutex' in namespace 'std' does not name a type"

### ISSUE THREAD

**Issue by qzylalala** [p-ranav/indicators#20]
on windows, when I run the code, it will throw this error  :  "error: 'mutex' in namespace 'std' does not name a type".  I google for it , somebody say "#include<mutex>" cannt work on windows.  I wanna know if there some solutions to solve this problem.  thanks a lot.

**Comment by p-ranav** [comment]
What compiler are you using? Visual Studio or MinGW or?

**Comment by qzylalala** [comment]
MinGW， I searched this problem in stackoverflow [https://stackoverflow.com/questions/14191566/c-mutex-in-namespace-std-does-not-name-a-type](url) . Maybe it doesnt work on windows ^^

**Comment by p-ranav** [comment]
I don't have much experience with MinGW but I seeing solutions that use the `MinGW Installation Manager` to install the `mingw32-pthreads-win32` dev package in `MinGW Standard Library`. Worth a shot?

**Comment by qzylalala** [comment]
Thank u for your suggestion, I will take a try on windows tomorrow. By the way, I succeeded in manjaro linux! thanks a lot^~^

**Comment by p-ranav** [comment]
@qzylalala Can this issue be closed?
