### ISSUE TITLE
Update project name and version?

### ISSUE THREAD

**Issue by xbreak** [p-ranav/indicators#26]
Thanks for this cool library!

It looks like the project was renamed indica -> indicators in 304226cbc5771d7c6ba4d67f9a779bb669156b80 but is still referred to as indica in CMakeLists.txt.  Additionally the [declared project version](https://github.com/p-ranav/indicators/blob/9a4729f5770d59dd5bb8c94c7471d9513cde5901/CMakeLists.txt#L2) does not match the tags & releases which can cause some confusion.

**Comment by p-ranav** [comment]
Sorry about that. Will update soon.
