### ISSUE TITLE
Single-header version

### ISSUE THREAD

**Issue by xelatihy** [p-ranav/indicators#29]
This is a really nice library. When deploying though it was a little bit more work than expected, given the library size. One possibility would be to have a single-header version of the library.
For example, CLI11 ( https://github.com/CLIUtils/CLI11) of JSON for modern C++ (https://github.com/nlohmann/json) follow this approach.

The single-header version can be generated with an amalgamation script. But, by looking at your code, it seems that it may be easier to use a single file, since many of the file have only a few lines of code.

If there is interest, but not enough development time, I would be happy to try to produce the one-file version by manually merging the existing code.

**Comment by p-ranav** [comment]
There is certainly interest. I'll take a crack at this soon.

**Comment by p-ranav** [comment]
You can find the single, merged header file in `single_include/indicators`.
