### ISSUE TITLE
Would it be possible to keep a progress bar at the bottom of the terminal?

### ISSUE THREAD

**Issue by prudhomm** [p-ranav/indicators#34]
In terminal applications such as apt (debian/ubuntu) the progress bar is kept at the bottom while some text is displayed regarding the progress of the installation.
Would it be possible to add such functionality?
Maybe it is not the scope of this library

**Comment by p-ranav** [comment]
In *nix, this is done with [ncurses](https://web.archive.org/web/20150815073411/http://math.hws.edu/orr/s04/cpsc225/curses.html). You could probably do this with some hardcoded escape sequences but it won't be pretty. Ncurses is the way to go, even if ncurses itself can be a little clunky. 

Yeah it is probably not in the scope of this library to add ncurses as a dependency.
