### ISSUE TITLE
Initializing time for dynamic progress

### ISSUE THREAD

**Issue by wolfv** [p-ranav/indicators#45]
We already have a property is_started, but currently time is accessed in the progress bar even if it's not initialized (started). 

This happens when a progress bar is printed from a dynamic multi (or probably also regular multi) bar, but no set_progress has been called.

Instead it should either print 00:00, or `--:--` for elapsed time if `is_started` is still false.

**Comment by p-ranav** [comment]
Pushed a fix for this. Please confirm and close.

**Comment by p-ranav** [comment]
@wolfv Can this be closed?
