### ISSUE TITLE
Windows cursor movements

### ISSUE THREAD

**Issue by wolfv** [p-ranav/indicators#46]
The dynamic progress bar uses ANSI escape codes for moving up and erasing lines. 

This doesn't work on Windows (and I could not make it work using `SetConsoleMode( ENABLE_VIRTUAL_TERMINAL_PROCESSING  |  ENABLE_VIRTUAL_TERMINAL_INPUT )`  either).

I found the following library for go which seems great: https://github.com/k0kubun/go-ansi

The following code works fine on Windows:

```
namespace cursor
{
    void move_up(int lines)
    {
        move(0, -lines);
    }

    void move_down(int lines)
    {
        move(0, -lines);
    }

    void move_left(int cols)
    {
        move(-cols, 0);
    }

    void move_up(int cols)
    {
        move(cols, 0);
    }

    void move(int x, int y) {
        auto hStdout = GetStdHandle(STD_OUTPUT_HANDLE); 
        if (!hStdout) return;

        CONSOLE_SCREEN_BUFFER_INFO csbiInfo;
        GetConsoleScreenBufferInfo(hStdout, &csbiInfo);

        COORD cursor;

        cursor.X = csbiInfo.dwCursorPosition.X + x;
        cursor.Y = csbiInfo.dwCursorPosition.Y + y;
        SetConsoleCursorPosition(hStdout, cursor);
    }

}
```

It would be nice to have more abstractions (also around finding the terminal windows size). Do you want to integrate these facilities into this library or should we create another one?

**Comment by wolfv** [comment]
Also just for the reference, one can simplify the ANSI codes used to move lines up. Instead of a for loop, by writing: `"\x1b[" << N << "A"` will move `N` lines up :)

**Comment by wolfv** [comment]
Ok I actually just double checked and 

```
    auto hStdout = GetStdHandle(STD_OUTPUT_HANDLE); 
    SetConsoleMode(hStdout, ENABLE_PROCESSED_OUTPUT | ENABLE_VIRTUAL_TERMINAL_PROCESSING);
```

seems to work as well (at least on Win 10).

**Comment by p-ranav** [comment]
I'm up for integrating these cursor movement functions in this library. It'd be good to support Windows better regarding this.

Another sticky point that will affect Windows is when we start calculating multi-byte character display width (using e.g., wcswidth in Linux) to better support unicode characters in progress bars. This is necessary to make sure the progress bar correctly displays in the configured `width`.
