### ISSUE TITLE
Windows "Illegal token on right side of ::"

### ISSUE THREAD

**Issue by kiliandys** [p-ranav/indicators#5]
Awesome lib.

I had trouble with usage of min/max on windows.

I will open a PR.

**Comment by kiliandys** [comment]
I can not create a pull requests.

Here is the problem (short recap):

- In termcolor.hpp, after `#include <windows.h>`

```cpp
#ifdef max
#undef max
#endif
#ifdef min
#undef min
#endif
```

- In progress_bar and progress_spinner, missing an include:
```
#include <algorithm>
```

**Comment by kiliandys** [comment]
Very good job on this repo, with the fix I suggest (probably not perfect) I can successfully use your library! Awesome!

**Comment by p-ranav** [comment]
Thanks for the report. Will fix this soon!

**Comment by p-ranav** [comment]
I don't like un-defining max and min as this could have adverse effects in other places in the application. Instead, I'll probably wrap the `std::min` call inside parenthesis and that should do it. https://stackoverflow.com/questions/1394132/macro-and-member-function-conflict

Alternatively, you could define `#define NONIMAX` before including the indicators headers and that might work.

**Comment by p-ranav** [comment]
Defined `NOMINMAX` in the progress bars and spinners before including `windows.h` in termcolor. Fixes the Windows build.
