### ISSUE TITLE
Indeterminate Progress Bar - update message

### ISSUE THREAD

**Issue by johughes99** [p-ranav/indicators#53]
I want to use the Indeterminate Progress Bar in my program - but where I update the message to indicate the stage an algorithm is in.  In the example the text "Checking for Updates" is shown. Is it possible to change this message dynamically whilst the bar is active?

**Comment by p-ranav** [comment]
Absolutely. Call `set_option` and set the postfix text:

```cpp
bar.set_option(option::PostfixText{"Algorithm Stage 2: Calculating foo"});  
```

**Comment by johughes99** [comment]
Brilliant, 

Thank you
