### ISSUE TITLE
Postfix string length grows

### ISSUE THREAD

**Issue by dd4e** [p-ranav/indicators#56]
Hello!

I use prefix and postfix for my interface
I use about 30 characters for postfix, but it prints 70 or more like this:
`
-- Info Checksum is correct·········································
`

My limit is 84 characters.
Why does string length increase with empty characters?

**Comment by p-ranav** [comment]
Can you paste your code here?

**Comment by dd4e** [comment]
I wrote a small example that repeats my problem

```c++
    // prepare progress bar
    auto prepare_p = [](ProgressBar *p, const std::string &prefix){
        p->set_option(option::PrefixText{prefix});
        p->set_option(option::Start{""});
        p->set_option(option::Fill{""});
        p->set_option(option::Lead{""});
        p->set_option(option::Remainder{""});
        p->set_option(option::End{""});
        p->set_option(option::BarWidth{0});
    };

    ProgressBar p1, p2;

    prepare_p(&p1, "Progress #1");
    prepare_p(&p2, "Progress #2");

    MultiProgress<ProgressBar, 2> mp(p1, p2);

    std::string some_text[] = {"foo", "bar", "independence", "beta", "alfa"};
    std::string dynamic_text;

    // first pb with static postfix text
    p1.set_option(option::PostfixText{"Static text"});

    // second pb with dynamic postfix text
    for (auto &t: some_text) {
        dynamic_text += t + " ";
        p2.set_option(option::PostfixText{dynamic_text});
        mp.set_progress<0>(0);
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }

    // update postfix to little text for pb #2
    p2.set_option(option::PostfixText{"abcd"});
    mp.set_progress<0>(0);
```

Result:
```
Progress #1 Static text···········
Progress #2 abcd··························································
```

* dot -- is space

**Comment by p-ranav** [comment]
Related to #42

**Comment by p-ranav** [comment]
Should be fixed now. Thanks for reporting this issue. 

![terminal_width](https://user-images.githubusercontent.com/8450091/82823987-22767080-9e6e-11ea-9925-13620a20dfab.gif)

**Comment by dd4e** [comment]
> Should be fixed now. Thanks for reporting this issue.
> 
> ![terminal_width](https://user-images.githubusercontent.com/8450091/82823987-22767080-9e6e-11ea-9925-13620a20dfab.gif)

Thank! How long to wait for a release with this fix?

**Comment by p-ranav** [comment]
Here you go: https://github.com/p-ranav/indicators/releases/tag/v1.9

**Comment by p-ranav** [comment]
Here you go: https://github.com/p-ranav/indicators/releases/tag/v1.9
