### ISSUE TITLE
cursor_control.hpp  show_console_cursor - multiple defintions

### ISSUE THREAD

**Issue by johughes99** [p-ranav/indicators#58]
Not really looked into this - as I have a work around. But if you have multiple includes of cursor_control.hpp in separate source files you get the error:

`pkcs11_progress.cpp:(.text+0x0): multiple definition of `indicators::show_console_cursor(bool)'
pkcs11_ec_ecdsaAttacks.o:pkcs11_ec_ecdsaAttacks.cpp:(.text+0x376): first defined here
`

**Comment by p-ranav** [comment]
Making this function `static inline` should fix the problem.

**Comment by p-ranav** [comment]
Please confirm if this fixes the problem.

**Comment by johughes99** [comment]
Fixed for me.
