### ISSUE TITLE
error: non-ISO-standard escape sequence, '\e'

### ISSUE THREAD

**Issue by dd4e** [p-ranav/indicators#62]
Hello!

When building release 1.9 with -Werror, an error occurs: "error: non-ISO-standard escape sequence, '\ e' [-Werror]"

[link to line](https://github.com/p-ranav/indicators/blob/master/single_include/indicators/indicators.hpp#L1573)

**Comment by p-ranav** [comment]
Paging @wolfv @felixguendling 

Hey guys. Is there an ISO-standards compliant way to show and hide console cursor in *nix?

Relevant code:
```cpp
static inline void show_console_cursor(bool const show) {
  std::fputs(show ? "\e[?25h" : "\e[?25l", stdout);
}
```

**Comment by felixguendling** [comment]
Seems like "\e" is GNU only and "\033" is the standard sequence.
Which compiler does produce this warning? Which settings are used? Compiling current master with GCC 9 worked fine for me. Currently, I cannot reproduce the warning/error.

**Comment by dd4e** [comment]
> Seems like "\e" is GNU only and "\033" is the standard sequence.
> Which compiler does produce this warning? Which settings are used? Compiling current master with GCC 9 worked fine for me. Currently, I cannot reproduce the warning/error.

This error is repeated only in release 1.9, there is no error in the master branch.

gcc version:
> gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008

compile keys:
> -Wall -Wextra -pedantic -Werror

diff maser->release 1.9
```
1573c1573
<   std::fputs(show ? "\033[?25h" : "\033[?25l", stdout);
---
>   std::fputs(show ? "\e[?25h" : "\e[?25l", stdout);
```

**Comment by p-ranav** [comment]
Okay, thanks. I've moved the tag for `v1.9` to the latest commit in master. Since this error doesn't occur in the master branch, v1.9 should work for you now.

**Comment by hueychen27** [comment]
@felixguendling Using `-Wpedantic` on `clang` produces that warning.
