### ISSUE TITLE
terminal_size.hpp error

### ISSUE THREAD

**Issue by picturetxl** [p-ranav/indicators#67]
` cols = csbi.srWindow.Right - csbi.srWindow.Left + 1;
  rows = csbi.srWindow.Bottom - csbi.srWindow.Top + 1;
  return {static_cast<size_t>(rows), static_cast<size_t>(columns)};`
columns should be cols

**Comment by bosmacs** [comment]
Any possibility of getting a 1.10 release with this fix? The current conan.io release (1.9) can't be used with MSVC.
