### ISSUE TITLE
TERMCOLOR_HPP_  define twice?

### ISSUE THREAD

**Issue by picturetxl** [p-ranav/indicators#68]
Why do you need to define TERMCOLOR_HPP_ twice in the header file in single_include, they are located on line 15 and line 667, which puzzles me

**Comment by p-ranav** [comment]
We don't. This is caused by the amalgamate script that generates the single include version of indicators. It shows that `<termcolor.hpp>` is redundantly included in a few places in the code. Will fix shortly.
