### ISSUE TITLE
#define NOMINMAX

### ISSUE THREAD

**Issue by Shot511** [p-ranav/indicators#72]
Use the following define before `#include <windows.h>` to avoid build errors on Windows using Visual Studio:

```
#define NOMINMAX
```

More info [here](https://stackoverflow.com/a/7035078/1892346).

P.S.
I'm using _single_include_ version.

**Comment by p-ranav** [comment]
It's already defined. See [here](https://github.com/p-ranav/indicators/blob/master/single_include/indicators/indicators.hpp#L920). Are you having build issues?

**Comment by Shot511** [comment]
Yes, I had build issues. I defined NOMINMAX before line 55 and now it builds perfectly.
