### ISSUE TITLE
Multiple include of the single header version lead to the multiple defined symbol error on windows

### ISSUE THREAD

**Issue by F-I-D-O** [p-ranav/indicators#80]
I had a hard time with this library after using the progress bar in a second file. The problem is on the following line:

https://github.com/p-ranav/indicators/blob/312c49bf9f24b3eaf0b591b56f844862823194bc/single_include/indicators/indicators.hpp#L678

After adding the inline specifier, everything works fine.

**Comment by p-ranav** [comment]
Thanks. Will add the inline specifier and update `master`
