### ISSUE TITLE
font color unchanged

### ISSUE THREAD

**Issue by xzhangxian1008** [p-ranav/indicators#81]
Kill the programme with Ctrl+C while it is running. The terminal can't change back to the original font color in Xshell.

![bug](https://user-images.githubusercontent.com/15918072/101880879-912ed780-3bce-11eb-97d6-236536d03703.png)

**Comment by p-ranav** [comment]
Although `indicators` does not directly handle the SIGINT signal, you can handle this like so:

```cpp
static inline void signal_handler(int signal) {
  indicators::show_console_cursor(true);
  std::cout << termcolor::reset;
  exit(signal);
}

int main() {
  // Register signal handler
  std::signal(SIGTERM, signal_handler);
  std::signal(SIGSEGV, signal_handler);
  std::signal(SIGINT, signal_handler);
```

This will call the signal handler when you `CTRL+C` and reset the terminal changes made by the library
