### ISSUE TITLE
Please don't re-define versions once published

### ISSUE THREAD

**Issue by Croydon** [p-ranav/indicators#83]
It seems like the version 1.9 got re-tagged after it was published first.

This is a huge problem and causes trust isues.

It breaks package manager like Conan who check downloads against checksums (ref. https://github.com/conan-io/conan-center-index/pull/4135) 

and it raises the question of stability and trustworthy. "Is this a bug? Has the project been hacked?"

So please don't do this again. Once a version is tagged it should never be redefined.

**Comment by p-ranav** [comment]
Yes, my bad. This will not happen again. Thanks for reporting the issue.
